# Generated by Django 4.2.1 on 2023-06-12 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='user_group',
            field=models.CharField(choices=[('student', 'student'), ('mentor', 'mentor')], default='student', max_length=10),
        ),
    ]
