# Generated by Django 4.1.7 on 2023-05-07 19:23

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mentor_app', '0002_question_user_first_name_user_groups_user_last_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('question1', models.IntegerField()),
                ('question2', models.IntegerField()),
                ('question3', models.IntegerField()),
                ('question4', models.IntegerField()),
                ('question5', models.IntegerField()),
                ('question6', models.IntegerField()),
                ('question7', models.IntegerField()),
                ('question8', models.IntegerField()),
                ('question9', models.IntegerField()),
                ('question10', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TenQuestionFormErasmo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('question1', models.IntegerField(verbose_name='Na ile oceniasz swoje umiejętności komunikacyjne z ludźmi z innych kultur? (1 - bardzo słabo, 10 - bardzo dobrze)?')),
                ('question2', models.IntegerField(verbose_name='Jak bardzo ważne jest dla Ciebie, aby Twój mentor miał podobne zainteresowania naukowe jak Ty? (1 - nieważne, 10 - bardzo ważne)')),
                ('question3', models.IntegerField(verbose_name='Jak bardzo jesteś samodzielny w rozwiązywaniu problemów? (1 - potrzebuję dużo pomocy, 10 - radzę sobie sam)')),
                ('question4', models.IntegerField(verbose_name='Jak istotne jest dla Ciebie uczestniczenie w wydarzeniach kulturalnych i towarzyskich organizowanych przez uczelnię? (1 - mało istotne, 10 - bardzo istotne)')),
                ('question5', models.IntegerField(verbose_name='Na ile ważne jest dla Ciebie, aby Twój mentor był dostępny w sytuacjach awaryjnych? (1 - nieważne, 10 - bardzo ważne)')),
                ('question6', models.IntegerField(verbose_name='Jak oceniasz swoją znajomość języka polskiego? (1 - nie znam, 10 - płynnie)')),
                ('question7', models.IntegerField(verbose_name='Na ile chciałbyś/abyś aktywnie uczestniczyć w życiu studenckim AGH? (1 - niezbyt aktywnie, 10 - bardzo aktywnie)')),
                ('question8', models.IntegerField(verbose_name='Jak bardzo cenisz sobie wsparcie w codziennych sprawach, takich jak zakupy, korzystanie z komunikacji miejskiej czy uczelnianych usług? (1 - nieważne, 10 - bardzo ważne)')),
                ('question9', models.IntegerField(verbose_name='Na ile ważne jest dla Ciebie, aby Twój mentor miał doświadczenie w pracy z uczniami z Twojego kraju? (1 - nieważne, 10 - bardzo ważne)')),
                ('question10', models.IntegerField(verbose_name='Jak bardzo chciałbyś/abyś otrzymać wsparcie w kwestiach związanych z nauką, takich jak nauka przedmiotów, egzaminy czy projekty? (1 - nieważne, 10 - bardzo ważne)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TenQuestionFormMentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('question1', models.IntegerField(verbose_name='Na ile oceniasz swoje umiejętności komunikacyjne z ludźmi z innych kultur? (1 - bardzo słabo, 10 - bardzo dobrze)')),
                ('question2', models.IntegerField(verbose_name='Jak bardzo ważne jest dla Ciebie, aby student, którym się opiekujesz, miał podobne zainteresowania naukowe jak Ty? (1 - nieważne, 10 - bardzo ważne)')),
                ('question3', models.IntegerField(verbose_name='Jak bardzo jesteś skłonny pomagać studentowi w rozwiązywaniu problemów? (1 - chciałbym unikać, 10 - z przyjemnością pomogę)')),
                ('question4', models.IntegerField(verbose_name='Jak istotne jest dla Ciebie uczestniczenie w wydarzeniach kulturalnych i towarzyskich organizowanych przez uczelnię wraz ze studentem? (1 - mało istotne, 10 - bardzo istotne)')),
                ('question5', models.IntegerField(verbose_name='Na ile jesteś w stanie być dostępny dla studenta w sytuacjach awaryjnych? (1 - trudno mi będzie, 10 - zawsze gotów do pomocy)')),
                ('question6', models.IntegerField(verbose_name='Jak oceniasz swoją umiejętność komunikacji w języku angielskim lub innym języku obcym, którym posługuje się student? (1 - nie znam, 10 - płynnie)')),
                ('question7', models.IntegerField(verbose_name='Na ile chciałbyś/abyś aktywnie uczestniczyć w życiu studenckim AGH wraz ze studentem? (1 - niezbyt aktywnie, 10 - bardzo aktywnie)')),
                ('question8', models.IntegerField(verbose_name='Jak bardzo chciałbyś/abyś pomagać studentowi w codziennych sprawach, takich jak zakupy, korzystanie z komunikacji miejskiej czy uczelnianych usług? (1 - nieważne, 10 - bardzo ważne)')),
                ('question9', models.IntegerField(verbose_name='Czy masz doświadczenie w pracy z uczniami z kraju, z którego pochodzi student? (1 - brak doświadczenia, 10 - dużo doświadczenia)')),
                ('question10', models.IntegerField(verbose_name='Jak bardzo chciałbyś/abyś wspierać studenta w kwestiach związanych z nauką, takich jak nauka przedmiotów, egzaminy czy projekty? (1 - nieważne, 10 - bardzo ważne)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='answers',
            field=djongo.models.fields.JSONField(),
        ),
    ]
