# Generated by Django 4.2.1 on 2023-06-12 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentor_app', '0003_alter_questions_user_group_mentoringchoices'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MentoringChoices',
            new_name='MentoringChoice',
        ),
    ]
