# Generated by Django 4.2.1 on 2023-06-12 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentor_app', '0004_rename_mentoringchoices_mentoringchoice'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FormAnswers',
            new_name='FormAnswer',
        ),
        migrations.RenameModel(
            old_name='Questions',
            new_name='Question',
        ),
    ]
