# Generated by Django 4.2.1 on 2023-06-12 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor_app', '0005_rename_formanswers_formanswer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mentorships_left',
            field=models.IntegerField(default=0),
        ),
    ]
